### ISSUE TITLE
mac won't awake

### ISSUE THREAD

**Issue by tylik1** [pirj/noclamshell#1]
I connected 2 external monitors and first time it worked fine, but the second time, mac wouldn't awake when lid is back to open. Had to restart the system.

**Comment by pirj** [comment]
Thanks for bringing this up, I'm experiencing the exact same issue time to time as well. It appears in roughly 10% of cases, so yeah, I have to reboot on each tenth lid open. Playing with params locally to work this around.

**Comment by pirj** [comment]
@tylik1 do you mind testing the new version please? It's been a while and I'm not experiencing unwanted restarts or wake denials. Your feedback would be invaluable.
