### ISSUE TITLE
Not working on M1 MacBook Air

### ISSUE THREAD

**Issue by cfstras** [pirj/noclamshell#10]
It seems that neither "AppleDisplay" nor "IODisplayWrangler" is present in the M1 `pmset`.

Here is a difference of `pmset -g powerstate` between lid closed and open:
```diff
--- powerstate.lidclosed        2021-03-01 21:01:37.000000000 +0100
+++ powerstate.regular  2021-03-01 21:01:45.000000000 +0100
@@ -332,12 +332,15 @@
 AppleDCPDPTXRemotePortPr    0          0  None
 AppleDCPDPTXRemotePortPr    1          1  USEABLE
 DCPDPDeviceProxy            0          0  None
+DCPDPDeviceProxy            0          0  None
 AppleCLCD2                  1          1  USEABLE
 AppleCLCD2                  1          1  USEABLE
 AppleSMC                    1          1  USEABLE
 AppleSmartBatteryManager    1          1  ON
 AppleDCPExpert              1          1  ON
 AppleDCPExpert              1          1  ON
+DCPDPDeviceProxy            0          0  None
+DCPDPDeviceProxy            0          0  None
 AppleCLCD2                  1          1  USEABLE
 AppleCLCD2                  1          1  USEABLE
 AppleHPMARM                 1          1  USEABLE
```

I've fixed the issue by adding these lines directly below `if [ "$LID_CLOSED" ]; then` in my `/opt/homebrew/bin/`:
```bash
CLAMSHELL=$(pmset -g powerstate | grep DCPDPDeviceProxy | wc -l)
if (( CLAMSHELL < 4 )); then
  pmset sleepnow
fi
```

Which seems like a really ugly hack, but it works for me. Don't know how to detect whether these should be present cleanly though... (`$(uname -m)  == "arm64"`)?

**Comment by pirj** [comment]
Wondering if this is architecture-related or OS version related. 🤔 
https://github.com/pirj/noclamshell/issues/9 may be related, but the author did not follow up.
What is your version of macOS?

**Comment by cfstras** [comment]
Running on Big Sur, 11.2.1 (20D74)

**Comment by pirj** [comment]
@half2me Can you please try with the above patch?

**Comment by half2me** [comment]
@pirj I don't have my external monitor atm so can't really test 🤷‍♀️

**Comment by cfstras** [comment]
@pirj If somebody wants to test this, I created a PR with the patch ready.
https://github.com/pirj/noclamshell/pull/11

**Comment by pirj** [comment]
Awesome, thank you! I'll test with my non-M1 non-BigSur tomorrow.

**Comment by mowen87** [comment]
just tried and patch worked for me on M1 MacBook Air

**Comment by benjamineskola** [comment]
Can also confirm this works on my M1 MacBook Air (running the Monterey beta).
