### ISSUE TITLE
Have to `brew services restart noclamshell` every few days. 

### ISSUE THREAD

**Issue by Coletrane** [pirj/noclamshell#12]
Every so often, usually about 3 -5 days I close my laptop and it goes into clamshell mode. I to run `brew services restart noclamshell` and it fixes it. The service appears to be running prior to this because the output of that command is: 
```
Stopping `noclamshell`... (might take a while)
==> Successfully stopped `noclamshell` (label: homebrew.mxcl.noclamshell)
==> Successfully started `noclamshell` (label: homebrew.mxcl.noclamshell)
```
Laptop is a 2020 Intel Macbook Pro 16in connected to an Asus display. Power + display in the same USB-C cable.

I have a cron job that restarts noclamshell automatically every day at noon, but this issue still happens.

**Comment by pirj** [comment]
Can you check with this patch https://github.com/pirj/noclamshell/pull/11?
What macOS version do you use?

**Comment by Coletrane** [comment]
MacOS Big Sur 11.4 (20F71)

**Comment by pirj** [comment]
Closing as stale. Hopefully, #11 fixed it.
