### ISSUE TITLE
cannot run at all

### ISSUE THREAD

**Issue by Fnalsk** [pirj/noclamshell#13]
big sur 11.6, macbook pro m1. After running `brew services start noclamshell` I get:

```
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/alpha/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist` exited with 5.
```

**Comment by mogzol** [comment]
I'm curious how you fixed this @Fnalsk because I'm getting the same error

**Comment by Fnalsk** [comment]
I believe I just reinstalled brew. It's been too long though and I may be misremembering.

**Comment by mmmago** [comment]
> I'm curious how you fixed this @Fnalsk because I'm getting the same error

`brew services restart noclamshell` worked for me.
