### ISSUE TITLE
How to use without Homebrew?

### ISSUE THREAD

**Issue by Mr-Jree** [pirj/noclamshell#14]
Hi,

I'd love to use this script but when I tried your code, it says brew command not found.

Thank you.

**Comment by pirj** [comment]
It's easy to fix. You need [Homebrew](https://brew.sh/).

If you prefer not to install Homebrew, put `noclamshell` script where you like it, e.g. `~/.bin`, and the [XML service descriptor](https://github.com/pirj/homebrew-noclamshell/blob/25af2e78581d99eacd32ff944c9048114e5580ea/Formula/noclamshell.rb#L14) to `~/Library/LaunchAgents` as `noclamshell.plist`. In this file, replace `#{plist_name}` with `nclamshell`, and `#{opt_bin}` with the path where you've put `noclamshell` script.
Thereafter, you'll have to launch it with `launchctl`. I suggest to check `man launchctl` for details.

**Comment by Mr-Jree** [comment]
Thank you sir, that worked.
