### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ShmuelTreiger** [pirj/noclamshell#15]
When I try running `brew services start noclamshell` I get permission denied error. When I use sudo, I get `Warning: noclamshell must be run as non-root to start at user login!` Not sure if this is a bug, user error, or a permission error with my company laptop (though I've installed homebrew scripts before with no issue). Appreciate any help! Thank you!
<img width="836" alt="Screen Shot 2021-11-29 at 11 47 12 AM" src="https://user-images.githubusercontent.com/14131043/143933466-cd5fa293-479f-429f-9e94-68a288dc48b7.png">

**Comment by pirj** [comment]
What is the output of `ls -la ~/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist`?

**Comment by ShmuelTreiger** [comment]
`ls: /Users/shmuel.treiger/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist: No such file or directory`

**Comment by pirj** [comment]
It looks like you don't have `noclamshell` installed. Or did you install it with `sudo`?
Should be (without `sudo`, using your user account):
```
brew install pirj/homebrew-noclamshell/noclamshell
```

**Comment by ShmuelTreiger** [comment]
When you said that, I thought maybe I had uninstalled it when it didn't work. But now I'm just unsure/confused

<img width="887" alt="Screen Shot 2021-11-30 at 11 00 01 AM" src="https://user-images.githubusercontent.com/14131043/144110715-7817aad8-ad27-4d56-98a6-c293d59f2569.png">

**Comment by pirj** [comment]
Hm. Maybe there's been some change to how tools from external taps are referred to in Homebrew. The log says
```
brew services start pirj/noclamshell/noclamshell
```
not just
```
brew services start noclamshell
```
Can you please try that?

**Comment by ShmuelTreiger** [comment]
Same issue
![Uploading Screen Shot 2021-12-01 at 2.09.34 AM.png…]()

**Comment by ShmuelTreiger** [comment]
Super appreciate your help figuring this out!

**Comment by pirj** [comment]
What's in that directory?
```
ls -la ~/Library/LaunchAgents
```
What if you reinstall the package?
```
brew reinstall pirj/homebrew-noclamshell/noclamshell
```

**Comment by ShmuelTreiger** [comment]
<img width="854" alt="Screen Shot 2021-12-01 at 10 32 54 AM" src="https://user-images.githubusercontent.com/14131043/144293155-ebd60fd0-85f3-4e66-8df6-6efa5d756323.png">

**Comment by pirj** [comment]
I don't see `noclamshell.plist` among files in `~/Library/LauchAgents`. It reports `total 16`, but I only see two. Is the output cut purposefully?

**Comment by ShmuelTreiger** [comment]
No, that's the full output. I see that now, super weird.

**Comment by ShmuelTreiger** [comment]
Super appreciate your help, but I feel bad taking your time. No worries if you want to chalk this up to a weird bug and close the issue.

**Comment by pirj** [comment]
Thanks for understanding. There seem to be a permissions issue on your machine with Homebrew, and there's nothing I can do to make things easier for you.

One general suggestion would be to reinstall everything Homebrew related. [`Brewfile`](https://github.com/Homebrew/homebrew-bundle) can be used to keep what you have installed.

**Comment by ShmuelTreiger** [comment]
Thanks! I'll give it a go!
