### ISSUE TITLE
Turn off display instead of sleep

### ISSUE THREAD

**Issue by y2kbaby2** [pirj/noclamshell#17]
Is there any way to trigger just turning off all the displays instead of going to sleep?

**Comment by pirj** [comment]
Doesn't this happen automatically in clamshell mode according to your power saving settings?

**Comment by y2kbaby2** [comment]
No, it waits for the 5 min or whatever the time is set to first

**Comment by pirj** [comment]
That's what I meant by "according to power saving settings".

This tool is already getting hard to maintain, I would prefer not to add more complexity to it.
Thanks for understanding.
