### ISSUE TITLE
"Failure while executing" on Big Sur

### ISSUE THREAD

**Issue by mmmago** [pirj/noclamshell#18]
`brew services start noclamshell`

returns

`
Error: Failure while executing; /bin/launchctl bootstrap gui/501 /Users/lucas/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist exited with 5.`

**Comment by pirj** [comment]
Maybe [this](https://github.com/pirj/noclamshell/issues/13) or [this](https://github.com/pirj/noclamshell/issues/15] can be helpful?
It looks something is wrong with Homebrew on your machine, there's nothing I can do code-wise to fix this.

**Comment by mmmago** [comment]
Re-installing homebrew did not work. I'm stuck :/

**Comment by mmmago** [comment]
@pirj ok weird stuff. `brew services restart noclamshell` solved the issue.

**Comment by meganlavengood** [comment]
had the same issue, "restart" worked but "start" didn't
