### ISSUE TITLE
homebrew services file

### ISSUE THREAD

**Issue by hartmms** [pirj/noclamshell#19]
Not really an issue, but a question.  I see this script uses "brew services", which I assume is a lot like linux systemd.  Where can I find a copy of the services file?  I'm curious how the noclamshell script is periodically called.   

I need this for my work laptop, but I can't install brew due to corporate policy.   I guess I could just setup a crontab to run noclamshell every X minutes. Do any of those commands require root access to run?

**Comment by pirj** [comment]
[Here's the service file](https://github.com/pirj/homebrew-noclamshell/blob/25af2e78581d99eacd32ff944c9048114e5580ea/Formula/noclamshell.rb#L19).
As far as I remember, macOS calls this service once in 2 seconds.

> Do any of those commands require root access to run?

No, it doesn't need escalated privileges, and  you can run them from your user.


You can definitely try with CRON. I don't have much experience with that, and I hope it won't run the script several times when waking from sleep periodically.
