### ISSUE TITLE
Machine fails to wake up

### ISSUE THREAD

**Issue by benbosman** [pirj/noclamshell#2]
I would love to have my MacBook sleep when I close the lid even though an external screen is connected. At the moment, I have to unplug the monitor (which also powers the laptop) to ensure it will go into standby mode.

I have a 2016 MacBook Pro, and used the script with an external USB-C screen attached, which also powers the machine.
Closing the lid caused the MacBook to crash each time (full system crash, and an automatic reboot afterwards).

I've temporarily removed the script using:
launchctl unload ~/Library/LaunchAgents/noclamshell.plist

It would be good to include this in your documentation as well.

**Comment by pirj** [comment]
@benbosman It seems that the recent fix for [Issue #1](https://github.com/pirj/noclamshell/issues/1) didn't work. I also experience crashes time to time.

Just pushed another fix for this problem. Appreciated for feedback. I've tested it, and never got a crash for ten times or so.

Added notes on how to disable the utility to Readme as well.

**Comment by benbosman** [comment]
@pirj Can you explain the reason for the sleep 10? It seems this is still causing issues.
I've deployed the new version, and added logging when the "pmset sleepnow" command is executed.
Closing the lid caused the command to be executed 6 times, each with a 10 second interval. Hereafter the full OS crashed with the message:
Event:           Sleep Wake Failure
This may be because there were 6 requests to sleep the laptop simultaneously.

**Comment by pirj** [comment]
@benbosman Have you also deployed the plist and unloaded and loaded it? It [has been changed](https://github.com/pirj/noclamshell/commit/4196e6b95109cad9484365bc6ac761b364fcd1a1) as well.

The reasoning for those changes was the fact that pmset was run concurrently, since putting the system to sleep takes a while and the job is being run several times. What has been done:
 - instead of running the job periodically every `n` seconds nevertheless if it's running already or not, I've changed it to wait `n` seconds between invocations. Even though `n` is quite low, 2 seconds, the script is only executed once per lid close because of the `sleep 10`.

Thanks for detailed feedback! Looking forward to see it working on your end.

**Comment by benbosman** [comment]
Yes I updated, copied, unloaded and reloaded the plist. This is probably why the interval was 10 seconds instead of 2.
I'll run some test by explicitly avoiding the "pmset sleepnow" command to be executed only once, and will let you know whether that helps. I'll share the changes if it works

**Comment by benbosman** [comment]
I've verified the script after applying some changes, and the problem seems to be the script is continuously executed even long after the "pmset sleepnow" command has been executed.
This has been verified using the attached script (and the plist from GIT)
[noclamshell.zip](https://github.com/pirj/noclamshell/files/707654/noclamshell.zip)
The "starting sleep mode at" note was logged at 8:05:57.
The "skipping sleep mode at" note was logged at 8:06:07 and every 2 seconds hereafter up until the moment I opened the lid again (at 8:33:55).

This may be specific to the MacBook model, but the changes did allow me to use the script without crashing my machine.

I didn't find a check yet to verify whether the machine was in sleep mode, and I also don't know why the script is still executed even though the external display is no longer receiving a signal. So I'm wondering whether this is the same sleep mode as you get without the script and without an external display attached.

**Comment by pirj** [comment]
@benbosman Thanks a lot for taking your time to dig this.

Basing on the logging from your script it takes 10-25 seconds for `sleepnow` to actually put the machine to sleep on my machine.

It works for me to set the sleep to 100, however it might be quite different on other machines. There is a downside to this approach: if you close, open and close the lid again it takes ~100 seconds to sleep again.

I've slightly modified your script, specifically:
- removed `sleep 10` altogether, since it's not reliable, and adds unpredictable side effects;
- removed parenthesis and ampersand around `pmset sleepnow` so that the script only exits when this command does;
- used a temporary file as semaphore. It might attempt to put the sleeping machine to sleep again because of the change in semaphore file name in between script runs (as $TMPDIR changes), but it won't be doing that in two second intervals causing failures.
- some cosmetics

Also played with `Enable Power Nap` option, works with both on and off.

Hope you still have patience left to try this one out! Would be very cool if we have a common ground and this version of the script works for both of us.

**Comment by benbosman** [comment]
@pirj I've been using the latest script (but with the additional logging I wrote before) for a few days now. And still my MacBook crashes when the script is executed for a while.
For example, I shut down my MacBook last night at 7:10, and the script triggered the sleep mode, but remained active (in the CLAMSHELL, but with the FLAG_FILE present) until a bit after midnight.
Hereafter my MacBook failed, and rebooted with the error message:
Event:           Sleep Wake Failure

It's unclear to me why the script keeps running after the sleep mode is activated. I can verify it again using the plist with StartInterval instead of ThrottleInterval, but it probably won't help

**Comment by pirj** [comment]
Had the same issue during the day today.
I've reduced the unknowns by keeping the flag file in HOME in my current:

    - FLAG_FILE=$TMPDIR/noclamshell.lid.closed.and.sleeping

    +FLAG_FILE=~/noclamshell.lid.closed.and.sleeping

Littering home directory is not a big deal, hope it works.

Will you play with `Enable Power Nap` on your machine?

**Comment by pirj** [comment]
Had a crash today.

**Comment by pirj** [comment]
Had another failure. Nothing interesting in the logs (/private/var/log/system.log).
However, in sleep logs (`pmset -g log`):

Before going to sleep:

    2017-01-25 14:48:32 +0700 Assertions            Summary- [System: No Assertions] Using AC(Charge: 100)

something around failed wake:

    2017-01-25 16:36:37 +0700 Assertions            Summary- [System: No Assertions] Using AC(Charge: 0)

I've set `hibernatemode`, `standby` and `autopoweroff` all to `0` for AC power as my machine is always on AC:

    sudo pmset -c hibernatemode 0
    sudo pmset -c standby 0
    sudo pmset -c autopoweroff 0

**Comment by pirj** [comment]
Yet another crash. Nothing in /private/var/log/system.log
However, in sleep log (`pmset -g log`):

Normally:

    Assertions            Summary- [System: No Assertions] Using AC(Charge: 100)

Somewhere around crash:

    Assertions            Summary- [System: No Assertions] Using AC(Charge: 0)

I decided to turn off hibernation completely, since I'm always on AC power:

    sudo pmset -c hibernatemode 0
    sudo pmset -c standby 0
    sudo pmset -c autopoweroff 0

Seems unrelated, but I also had to:

    sudo pmset -a disksleep 1

because of this warning:

    Warning: Idle sleep timings for "Battery Power" may not behave as expected.
    - Disk sleep should be non-zero whenever system sleep is non-zero.

**Comment by pirj** [comment]
Still experiencing failures to wake up. Reverted back to original values:

    sudo pmset -c hibernatemode 3
    sudo pmset -c standby 1
    sudo pmset -c autopoweroff 1

Also this (forgot to check my previous setting):

    sudo pmset -a lidwake 1

**Comment by benbosman** [comment]
I've been testing the sleep mode without the script for a bit, to verify in detail how it works. I did explicitly tell my MacBook to sleep while the power and external screen were connected. What I noticed is:
1. My machine no longer crashed (so the crashes were indeed related to the script)
2. Even when I explicitly asked my machine to sleep, it kept a few things alive. My office VPN connection survived an entire night with the MacBook in sleep (while it disconnects automatically if the machine is not powered and put to sleep mode)
3. Sometimes my MacBook turns itself on again, with the both screens displaying the login window. It will not disable the displays automatically in that case, and I have to manually put it back to sleep

I'm searching for a way to verify whether either:
- The machine is in sleep mode (while apparently still being active)
- The displays are in sleep mode

But no luck in finding this (but I'm not familiar with the Apple specific commands). If you can help me find these, I can try another iteration at adjusting the script.

**Comment by pirj** [comment]
Never happened to me for past month or so, I suppose this is related to some 10.12 update, I'm on 10.12.6 now. How about you, Ben?

**Comment by pirj** [comment]
Never happened to me on High Sierra for few days already.

Going to leave this here anyway:
```
Sometimes when your Mac is running on AC power it won't wake up and will require Alt-Cmd-Power to reboot it.
To work around this issue, you should either disable hibernation completely (-c means AC powered):

    sudo pmset -c hibernatemode 0
    sudo pmset -c standby 0
    sudo pmset -c autopoweroff 0

That way if you experience power loss, you will have to cold boot your machine.

Back to defaults:

    sudo pmset -a hibernatemode 3
    sudo pmset -a standby 1
    sudo pmset -a autopoweroff 1
```
