### ISSUE TITLE
Had to reinstall after upgrade from Big Sur to Monterey

### ISSUE THREAD

**Issue by nabilfreeman** [pirj/noclamshell#20]
No complaints really, just letting you know this happened. Error I got while trying to manually start after upgrade:

```
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/xxx/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist` exited with 5.
```

Uninstalled and reinstalled as per README and all good again.

**Comment by pirj** [comment]
Understood.
Do you want to send a PR adding a note to the README?
