### ISSUE TITLE
Doesn't sleep the same way it does when manually triggered

### ISSUE THREAD

**Issue by epiller** [pirj/noclamshell#21]
It seems the sleep initiated by noclamshell isn't the same as the one when you manually enter sleep mode on M1.  
Here's how noclamshell sleep differs from normal sleep:  
- Plugged in USB devices continue being powered (with manual seep the USB devices go offline)
- When the lid is opened, it seems to come back quicker (as if just the display was off) compared to when I manually put it in sleep
- It remains connected to the network (while with normal sleep it kills all connections after about 5 seconds)
- I can feel the laptop being slightly warm even when it has been closed (with external monitor sleeping) for several hours - indicating it isn't really sleeping  

Keep in mind all other behavior is the same as normal (manually triggered) sleep.  
Kudos!

**Comment by Brawl345** [comment]
I have a Macbook Pro 2021 with an M1 Max and for me it's working like manual standby. I have a USB-C dock with an external hard drive connected and it powers down correctly.

**Comment by epiller** [comment]
It might have been an edge case or something. I'll close it.
