### ISSUE TITLE
Error: Cannot install on m1 Mac

### ISSUE THREAD

**Issue by Lukas604** [pirj/noclamshell#23]
Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
Please create a new installation in /opt/homebrew using one of the
"Alternative Installs" from:
  https://docs.brew.sh/Installation
You can migrate your previously installed formula list with:
  brew bundle dump

**Comment by pirj** [comment]
This level of detail is insufficient to reproduce/understand the issue.
It seems that Homebrew is suggesting you how to fix it, can you please try to follow?
Is it installing other packages just fine?
