### ISSUE TITLE
Mac m1 pro not going to sleep

### ISSUE THREAD

**Issue by piyu-sh** [pirj/noclamshell#24]
Hey @pirj , first of all, thanks for this tool, because this seems like the only tool that actually is working for a lot of people.
Unfortunately not for me.

Problem:
Installed the service and started it, also I keep an external display, mouse, keyboard connected through usb c.
But whenever I disconnect charger and close the lid, I expect that it should go to sleep with your service, but I doubt it sleeps because the next day battery is still very low like it used to be without this service.
Check the battery usage over Weekend(S and S in pic), its almost 0 after that
<img width="330" alt="image" src="https://github.com/pirj/noclamshell/assets/7107647/8d20e7b5-5651-4740-bed4-5ceba386796d">

Also if I disconnect all the external devices, and disconnect charger and close the lid, it would go to sleep no problem. But in that case it goes to sleep without this service as well.

This is what `brew services list` shows:
<img width="953" alt="image" src="https://github.com/pirj/noclamshell/assets/7107647/d0def81b-857e-4877-95cb-c93c95de916e">

I hope you can help me.
Thanks.

**Comment by pirj** [comment]
> whenever I disconnect charger and close the lid, I expect that it should go to sleep

What’s on your external screen? Does it turn off?

To debug, run just the executable file, periodically, from the command line. E.g
‘’’
watch /opt/himebrew/…
‘’’

and add some echo statements to output inputs used to make decisions in conditional statements.

please let me know if you need details on any of that.

**Comment by pirj** [comment]
I hope the issue was resolved. If ut stull doesn’t work - feel free to provide more info for debugging.
