### ISSUE TITLE
`Bootstrap failed: 5: Input/output error` on start

### ISSUE THREAD

**Issue by kaiserkiwi** [pirj/noclamshell#25]
Hi there, just wanted to test this script. I'm on a MacBook 16" with M1 Pro.

After installing and starting I just get the mentioned Error.
The complete output is
```bash
~ brew services start noclamshell          
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/mkr/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist` exited with 5.
```

If I look at `brew services list` it's visible there, but "scheduled".

Here a screenshot of my full terminal until the error.
<img width="1578" alt="Bildschirmfoto 2024-01-26 um 11 02 20" src="https://github.com/pirj/noclamshell/assets/8428551/8af8764d-9c75-49b0-8145-4f826985663a">

**Comment by pirj** [comment]
Thanks for reporting.
What happens if you run the `/bin/launchctl ` command directly? I’m unaware what bootstrap, gui are and why homebrew runs that.

**Comment by kaiserkiwi** [comment]
Well. That's disappointing 😅 
<img width="868" alt="image" src="https://github.com/pirj/noclamshell/assets/8428551/01f77d56-282b-463d-b7ce-a5e5565bd701">
If I can give any more info that helps, let me know.

**Comment by pirj** [comment]
I look at [this](https://github.com/pirj/nobacklight#installation) and think what if you run `launchctl load` with a plist instead of this weird bootstrap?

**Comment by kaiserkiwi** [comment]
Weirdly the same error. I guess something with my homebrew is broken. It only affects this app so far, but I think you can't do anything about it. Thanks for your time and sorry for bothering you with it.

**Comment by pirj** [comment]
I have the same issue with ‘laynchctl load’ and ‘launchctl bootstrap’ locally.
However, ‘launchctl start’ with a full path to the plist file works fine.
‘brew services start noclamshell’ runs fine, too

If ‘launchctl start’ would work for you, i suggest opening a ticket in homebrew and ask what do they do with load/bootstrap that fails

**Comment by kaiserkiwi** [comment]
The problem doesn't exist for me on my new MacBook Pro M4 Max. So probably still an issue for some, but not for me, so I will unsubscribe this.
