### ISSUE TITLE
Eject external drives before sleep?

### ISSUE THREAD

**Issue by davidrips** [pirj/noclamshell#26]
Hi, not sure if you have the bandwith for this specific use case, but figured I'd ask. I keep my M2 Air plugged in to a hub that charges, connects to ethernet, monitor, and also my Time Machine backup external drive. When I close my lid and the mac goes to sleep, once I turn it back on, I have notifs that the drive was ejected incorrectly. 

I have the app Ejectify (https://ejectify.app) which is supposed to automatically eject the drives when the mac goes to sleep, but it does not work consistently, and I got the thought that maybe it has some sort of conflict with how noclamshell puts the computer to sleep. I don't know how their app works exactly, and I obviously don't expect you to know how might interact - but is there anything in particular you can tell me about how noclamshell puts the computer to sleep that differs significantly from the normal process of putting it to sleep? That might give me a lead to go to Ejectify's devs about.

**Comment by pirj** [comment]
Hi, thanks for reporting. I’ve been getting this warning for years, too. I haven’t heard about Ejectify. What mode are you using, “when the system starts sleeping”? Have you tried “force eject”?

**Comment by pirj** [comment]
Ejectify provides a comprehensive [debug checklist](https://github.com/nielsmouthaan/ejectify-macos?tab=readme-ov-file#why-do-i-still-receive-notifications).

I’ll be happy to provide a hook (would run a binary if present before sleeping) to smooth things up.
