### ISSUE TITLE
M1 MacBook turns all displays on when notification arrives

### ISSUE THREAD

**Issue by JanBilek111** [pirj/noclamshell#28]
Hi, first, thank you all for this tool.

It seems that my M1 Mac  goes to sleep when lid is closed with external screen connected, and all screens go to standby - that is desired behaviour. However I have noticed that all screens goes on for a brief moment when notification is received - like new iMessage etc. after few seconds all screens go off again. Is this expected? Can I change this behaviour?

Thanks
Jan

**Comment by pirj** [comment]
Hi! Thanks for reporting, this is indeed an annoying problem.
I’ve noticed that Mac sometimes wakes up, but it doesn’t attempt to turn the sceeb on. I don’t use iMessage, thiugh. Can you reproduce this with no external screen connected, and lid open, and you just let the laptop go to sleep?

**Comment by pirj** [comment]
Ping

**Comment by JanBilek111** [comment]
Sorry for late reply, when I disconnect all screens, manually put mac to sleep and try to initiate a notification - I tried to switch DND mode off - the behaviour is the same. Mac screen goes on.

**Comment by pirj** [comment]
I guess this is just how mac behaves. I don’t know if there’s a setting not to wake it up. But this seems unrelated to the noclamshell utility.
