### ISSUE TITLE
Add version number for latest version on master

### ISSUE THREAD

**Issue by szhu** [pirj/noclamshell#3]
I made a Homebrew formula, but version 1.0 is outdated, and the current version does not have a version number. Please tag 3c540e8 with a version number.

Here is the formula as is:
https://github.com/szhu/homebrew-personal/blob/master/Formula/noclamshell.rb

```
brew install szhu/personal/noclamshell
brew services start noclamshell
```

**Comment by pirj** [comment]
Tagged as 1.1
https://github.com/pirj/noclamshell/releases/tag/1.1
Thanks for the formula!
