### ISSUE TITLE
This seems eat lots of CPU resource 

### ISSUE THREAD

**Issue by Songyu-Wang** [pirj/noclamshell#6]
Oh boy, I am wondering why my laptop keeps freeze everyday with high CPU usage for a long time until I remember this. Tried to turn this off, and I can't even hear the fan anymore....

Is there any optimization we can do to slow this down? like run the loop every second?

(duplicated https://github.com/pirj/noclamshell/issues/5 because I created the issue with wrong account)

**Comment by pirj** [comment]
As far as I remember how those cryptic Launch Agent settings work, it runs the script every two seconds, and it's not even a loop. https://github.com/pirj/homebrew-noclamshell/blob/master/Formula/noclamshell.rb#L19
```xml
<key>ThrottleInterval</key> <integer>2</integer>
```

This file is in `/usr/local/opt/noclamshell/homebrew.mxcl.noclamshell.plist` (there's yet another one you shouldn't touch, it's I guess is Homebrew cache `/usr/local/Cellar/noclamshell/1.1/homebrew.mxcl.noclamshell.plist`).
Can you try to play with this setting? For the changes to take effect, you'll have to run:
```
brew services stop noclamshell
# edit /usr/local/Cellar/noclamshell/1.1/homebrew.mxcl.noclamshell.plist
brew services start noclamshell
```
NOTE: Please make sure your CPU goes down to idle after stopping it.

NOTE: Please do not edit `~/Library/LaunchAgents/homebrew.mxcl.noclamshell.plist`, it gets deleted when you `stop`, and is copied over from `/usr/local/opt/noclamshell/homebrew.mxcl.noclamshell.plist`.



There's yet another thing I'll ask you to do to resolve the issue.
Can you try running the script manually and check if it consumes CPU on its own?
Then, run the following command and see if it is suspiciously slow or bursts the CPU:
```sh
bash -c /usr/local/bin/noclamshell
```
It will correspond to how it's run by the service (plist file): https://github.com/pirj/homebrew-noclamshell/blob/master/Formula/noclamshell.rb#L23



By the way, did this happen after Catalina upgrade? I've heard really bad things about it. Before running arbitrary scripts it tends to open a connection to some server, send some data, get a response, and only run the script afterwards. This, as reported, may take several seconds. I'm not sure if it could throttle your CPU, but is worth investigating.


Please let me know how it works for you.
I'm on 10.14, and it stopped working for me at some random point of time.

**Comment by pirj** [comment]
Update: it suddenly started working for me!

**Comment by Songyu-Wang** [comment]
@pirj Thank you for your reply, my mac version is 10.15.4. It is a new laptop, so this is the version I got with. However, I never experienced this on my old mac (with a cant remember old version and it is not available anymore)
I can try to find some time to look into this, but idk when that would be.

**Comment by Songyu-Wang** [comment]
hmmm, I uninstalled it and reinstalled it.
After staring the service, I do not experience high cpu usage anymore? 
Not sure what happened. 
Gonna close this issue for now, and if this issue surface again, then it probably means it is accumulating something somewhere.
I will reopen this then

**Comment by pirj** [comment]
Great to know you've managed to solve it so easily!
