### ISSUE TITLE
Not working with macOS Big Sur

### ISSUE THREAD

**Issue by istephan** [pirj/noclamshell#7]
Unfortunately I get the following responses when trying to install the package via Terminal / Homebrew:

Error: Your CLT does not support macOS 11.0.
Error: Formula `noclamshell` is not installed.

When I run the file from the zip-archive, it tells me:

[Process completed]

Unfortunately it doesn't work afterwards.

**Comment by pirj** [comment]
Run `xcode-select --install` and then repeat:
```
brew install pirj/homebrew-noclamshell/noclamshell
brew services start noclamshell
```

From: https://stackoverflow.com/questions/9329243/how-to-install-xcode-command-line-tools

If there's still an issue, please provide full traces on what you run and what errors are.
