### ISSUE TITLE
Didn't seem to work for me on Big Sur 11.1

### ISSUE THREAD

**Issue by half2me** [pirj/noclamshell#9]
Hi, I've just checked it out, the service is running, but closing the lid just behaves as it always did, and the macbook stays on.
Is there any extra step I'm missing?

**Comment by pirj** [comment]
No, that should be it.
Can you please try from your console:
```
$ /usr/local/bin/noclamshell
```
does it output any error messages?

What happens if you run the following and quickly close your lid?
```
$ sleep 5 && /usr/local/bin/noclamshell
```

We'll see from there what might be wrong.

**Comment by pirj** [comment]
Closing as stale.
Please feel free to reopen provided more details.
